---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service2
  name: service2
  namespace: argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service2
    spec:
      containers:
      - image: 769187045176.dkr.ecr.us-west-1.amazonaws.com/zi_service2:latest
        name: zi-service2
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service2
  name: service2
  namespace: argo
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: service2
status:
  loadBalancer: {}
