---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service1
  name: service1
  namespace: argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service1
    spec:
      containers:
      - image: 769187045176.dkr.ecr.us-west-1.amazonaws.com/zi_service1:latest
        name: zi-service1-brf9s
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service1
  name: service1
  namespace: argo
spec:
  ports:
  - nodePort: 31819
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: service1
  type: NodePort
